version:  "3"
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro  # relative path
    environment:
      - NODE_ENV=development
    command: npm run start-dev
